paths:
  migrations: '%%PHINX_CONFIG_DIR%%/../migrations'
  seeds: '%%PHINX_CONFIG_DIR%%/../seeds'

environments:
  default_migration_table: phinxlog
  default_database: development
  production:
    adapter: pgsql
    host: localhost
    name:
    user:
    pass: ''
    port: 5432
    charset: utf8

  development:
    adapter: pgsql
    host: localhost
    name:
    user:
    pass: ''
    port: 5432
    charset: utf8

  testing:
    adapter: pgsql
    host: localhost
    name:
    user:
    pass: ''
    port: 5432
    charset: utf8

version_order: creation
